language: php
php:
  - 5.6
install:
  - composer self-update
  - composer install --dev
script:
  - vendor/bin/phpunit --disallow-test-output --report-useless-tests --strict-coverage -d error_reporting=-1 --coverage-clover=build/logs/clover.xml Tests
